ansible_user: ubuntu
ansible_ssh_private_key_file: "~/.ssh/zookeeper-keypair.pem"

zookeeper_version: "3.9.5"

zookeeper_install_dir: "/opt/zookeeper"
zookeeper_config_dir: "/etc/zookeeper"
zookeeper_data_dir: "/data/zookeeper/data"
zookeeper_datalog_dir: "/data/zookeeper/log"
zookeeper_log_dir: "/var/log/zookeeper"

zookeeper_heap: "256M"

zookeeper_client_port: 2181
zookeeper_quorum_port: 2888
zookeeper_election_port: 3888

backup_enabled: true
backup_frequency: "daily"
backup_retention_days: 7
backup_path: "/backup/zookeeper"
backup_type: "full"

restore_enabled: true
restore_type: "full"
restore_target: "zk1"
restore_backup: "20260608_084921"

