[web]
node1 ansible_host=172.18.0.2 app_port=8000 app_env=production nginx_port=80
node3 ansible_host=172.18.0.5 app_port=8000 app_env=production nginx_port=80

[db]
node2 ansible_host=172.18.0.3

[common:children]
web
db

[common:vars]
ansible_user=ansible
ansible_ssh_private_key_file=/root/.ssh/id_ed25519
ansible_ssh_common_args=-o StrictHostKeyChecking=no
