---
- name: Check ZooKeeper health
  shell: echo ruok | nc 127.0.0.1 2181
  register: ruok_result
  changed_when: false

- name: Show ruok result
  debug:
    msg: "{{ ruok_result.stdout }}"

- name: Verify ensemble size
  shell: echo mntr | nc 127.0.0.1 2181 | grep zk_server_state
  register: ensemble_result
  changed_when: false

- name: Show ensemble result
  debug:
    msg: "{{ ensemble_result.stdout }}"

- name: Check metric text
  shell: echo mntr | nc 127.0.0.1 2181
  register: mntr_result
  changed_when: false

- name: Show mntr result
  debug:
    msg: "{{ mntr_result.stdout }}"

- name: Check ports listening
  shell: ss -lntp | egrep '{{ zookeeper_client_port }}|{{ zookeeper_quorum_port }}|{{ zookeeper_election_port }}'
  register: port_result
  changed_when: false

- name: Show ports result
  debug:
    msg: "{{ port_result.stdout }}"

- name: Check quorum ports
  shell: ss -antp | egrep '{{ zookeeper_quorum_port }}|{{ zookeeper_election_port }}'
  register: port_result2
  changed_when: false

- name: Show quorum ports result
  debug:
    msg: "{{ port_result2.stdout }}"

- name: Check process
  shell: ps -ef | grep QuorumPeerMain
  register: process_result
  changed_when: false

- name: Show process result
  debug:
    msg: "{{ process_result.stdout }}"

- name: Check log
  shell: journalctl -u zookeeper -n 50 --no-pager
  register: log_result
  changed_when: false

- name: Show log result
  debug:
    msg: "{{ log_result.stdout }}"

- name: Test write data
  shell: >
    echo "create /ha_test 'ok'" |
    /opt/zookeeper/current/bin/zkCli.sh
    -server {% for host in groups['zookeeper'] %}{{ hostvars[host]['ansible_host'] }}:{{ zookeeper_client_port }}{% if not loop.last %},{% endif %}{% endfor %}
  args:
    executable: /bin/bash
  register: zkcli_result
  changed_when: false
  run_once: true
  ignore_errors: true

- name: Test read data
  shell: >
    echo "get /ha_test" |
    /opt/zookeeper/current/bin/zkCli.sh
    -server {% for host in groups['zookeeper'] %}{{ hostvars[host]['ansible_host'] }}:{{ zookeeper_client_port }}{% if not loop.last %},{% endif %}{% endfor %}
  args:
    executable: /bin/bash
  register: get_result
  changed_when: false
  run_once: true

- name: Show read result
  debug:
    msg: "{{ get_result.stdout }}"
  run_once: true