---
- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Allow Zookeeper
  ufw:
    rule: allow
    port: '{{ zookeeper_client_port }}'
    proto: tcp

- name: Allow Zookeeper
  ufw:
    rule: allow
    port: '{{ zookeeper_quorum_port }}'
    proto: tcp

- name: Allow Zookeeper
  ufw:
    rule: allow
    port: '{{ zookeeper_election_port }}'
    proto: tcp

- name: Enable firewall
  ufw:
    state: enabled
    default: deny

- name: Reload ufw
  ufw:
    state: reloaded

- name: Status ufw
  command: ufw status
  register: ufw_status

- name: Show result
  debug:
    msg: "{{ ufw_status.stdout }}"