---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install basic packages
  apt:
    name:
      - curl
      - vim
      - net-tools
    state: present

- name: Create deploy user
  user:
    name: deploy
    state: present
    shell: /bin/bash
