---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install basic packages
  apt:
    name:
      - curl
      - vim
      - net-tools
      - sysstat
      - fio
    state: present

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Install Java and required tools
  apt:
    name:
      - openjdk-17-jre-headless
      - wget
      - tar
      - netcat-openbsd
    state: present
    update_cache: yes

- name: Install Chrony
  apt:
    name:
      - chrony
    state: present
    update_cache: yes

- name: Enable and start Chrony service
  systemd:
    name: chrony
    enabled: yes
    state: started

- name: Check Chrony tracking status
  command: chronyc tracking
  register: chrony_result

- name: Display Chrony tracking result
  debug:
    msg: "{{ chrony_result.stdout }}"

- name: Check NTP sources
  command: chronyc sources
  register: sources_result

- name: Display Chrony sources result
  debug:
    msg: "{{ sources_result.stdout }}"

- name: Add hosts entries
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  loop: "{{ groups['zookeeper'] }}"

- name: Verify hosts resolution
  command: getent hosts {{ item }}
  register: host_result
  loop: "{{ groups['zookeeper'] }}"
  changed_when: false

- name: Display hosts resolution result
  debug:
    msg: "{{ item.stdout }}"
  loop: "{{ host_result.results }}"